### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by rnadler** [cpbotha/xdg-open-wsl#4]
Using WSL 1 with Python 3.5.2
```
$ xdg-open
  File "/home/bobn/bin/xdg-open", line 39
    table.append((f"{mount_point}/", drive[0:-1] + "/"))
                                  ^
SyntaxError: invalid syntax
```
Do I need to use a more recent version of phython3?

**Comment by jornh** [comment]
@rnadler Yes, at least python 3.6, what it chokes on above is an f-string: https://www.python.org/dev/peps/pep-0498/

**Comment by cpbotha** [comment]
Thank you @jornh -- confirmed that this requires at least Python 3.6, as is also indicated in the pyproject.toml
